apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: default
  labels:
    app: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: mkowalew/auth-api:latest
          env:
            - name: MARIADB_HOST
              valueFrom:
                secretKeyRef:
                  name: identitydb-secret
                  key: MARIADB_HOST
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: identitydb-secret
                  key: MARIADB_ROOT_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identitydb-secret
                  key: MARIADB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: identitydb-secret
                  key: MARIADB_DATABASE
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-lb
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: auth-api