apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-api-service
          image: your-dockerhub-username/auth-service:latest
          env:
            - name: MARIADB_HOST
              valueFrom:
                secretKeyRef:
                  name: identitydb-creds
                  key: MARIADB_HOST
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: identitydb-creds
                  key: MARIADB_ROOT_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identitydb-creds
                  key: MARIADB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: identitydb-creds
                  key: MARIADB_DATABASE
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-lb
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: auth-service