apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "" 
  volumeName: identity-pv
