apiVersion: v1
kind: Secret
metadata:
  name: identitydb-secret
  namespace: default
type: Opaque
data:
  # Base64 encode your values using: echo -n 'value' | base64
  MARIADB_ROOT_USERNAME: cm9vdA==   # "root" (base64 encoded)
  MARIADB_ROOT_PASSWORD: cGFzc3dvcmQ=   # "password" (base64 encoded)
  MARIADB_DATABASE: aWRlbnRfbWdtdA== # "ident_mgmt" (base64 encoded)
