apiVersion: v1
kind: Service
metadata:
  name: retaildb-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: identitydb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
